prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/dinamic_card_catalog.sql
@@application/shared_components/navigation/lists/dinamic_card_catalog_perfil.sql
@@application/shared_components/navigation/lists/dinamic_card_menu.sql
@@application/shared_components/navigation/lists/dinamic_card_menu_perfil.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/theme_region_murcia_css.sql
@@application/shared_components/files/theme_region_murcia_min_css.sql
@@application/shared_components/files/escudo_texto_carm_png.sql
@@application/shared_components/files/escudo_texto_carm_transparente_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/escudo_texto_carm_transparente_2_png.sql
@@application/shared_components/files/carm_cap5_simbolo_tablets_css.sql
@@application/shared_components/files/escudo_carm_transparente_png.sql
@@application/shared_components/files/carm_cap5_simbolo_tablets_min_css.sql
@@application/shared_components/files/nextgenerationeu_png.sql
@@application/shared_components/files/igutil_js.sql
@@application/shared_components/files/igutil_min_js.sql
@@application/shared_components/files/mus_manualusuario_eduredeja_0100_sinlogo_pdf.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/ticket.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/list_cod_estado_portafirmas.sql
@@application/shared_components/user_interface/lovs/list_ejercicios.sql
@@application/shared_components/user_interface/lovs/list_estado_firma.sql
@@application/shared_components/user_interface/lovs/list_estado_notificacion.sql
@@application/shared_components/user_interface/lovs/list_estado_procesado_file.sql
@@application/shared_components/user_interface/lovs/list_notificacion_anexo.sql
@@application/shared_components/user_interface/lovs/list_notificacion_automatica_anexos.sql
@@application/shared_components/user_interface/lovs/list_notificar_a.sql
@@application/shared_components/user_interface/lovs/list_organismos.sql
@@application/shared_components/user_interface/lovs/list_organismos_disponibles.sql
@@application/shared_components/user_interface/lovs/list_organismos_total.sql
@@application/shared_components/user_interface/lovs/list_origen_documento.sql
@@application/shared_components/user_interface/lovs/list_pais_nacionalidad.sql
@@application/shared_components/user_interface/lovs/list_roles.sql
@@application/shared_components/user_interface/lovs/list_servicios.sql
@@application/shared_components/user_interface/lovs/list_status_fact.sql
@@application/shared_components/user_interface/lovs/list_tipo_notificacion.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/lst_asunto.sql
@@application/shared_components/user_interface/lovs/lst_clase.sql
@@application/shared_components/user_interface/lovs/lst_clasificacion.sql
@@application/shared_components/user_interface/lovs/lst_clas_calor.sql
@@application/shared_components/user_interface/lovs/lst_clas_seguridad.sql
@@application/shared_components/user_interface/lovs/lst_finalidad.sql
@@application/shared_components/user_interface/lovs/lst_municipios.sql
@@application/shared_components/user_interface/lovs/lst_municipios_fun.sql
@@application/shared_components/user_interface/lovs/lst_objeto_declaracion.sql
@@application/shared_components/user_interface/lovs/lst_plantilla.sql
@@application/shared_components/user_interface/lovs/lst_provincias.sql
@@application/shared_components/user_interface/lovs/lst_tipo_documento.sql
@@application/shared_components/user_interface/lovs/lst_tipo_instalacion.sql
@@application/shared_components/user_interface/lovs/lst_tipo_interesado.sql
@@application/shared_components/user_interface/lovs/lst_tipo_persona.sql
@@application/shared_components/user_interface/lovs/lst_tipo_sexo.sql
@@application/shared_components/user_interface/lovs/lst_tipo_utm.sql
@@application/shared_components/user_interface/lovs/lst_tramite.sql
@@application/shared_components/user_interface/lovs/lst_uso.sql
@@application/shared_components/user_interface/lovs/lst_usuarios.sql
@@application/shared_components/user_interface/lovs/perfiles_nombre.sql
@@application/shared_components/user_interface/lovs/si_no.sql
@@application/shared_components/user_interface/lovs/tabla_tipo_datos_descripcion.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/acceso_aplicacion.sql
@@application/shared_components/security/authentications/autencicacion_singel_sing_on.sql
@@application/shared_components/security/authentications/ticket.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/plugins/item_type/com_fos_progress_bar.sql
@@application/shared_components/plugins/region_type/com_oracle_apex_display_source.sql
@@application/shared_components/plugins/dynamic_action/rw_apex_client_timer.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00040.sql
@@application/pages/page_00050.sql
@@application/pages/page_00060.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00120.sql
@@application/pages/page_00130.sql
@@application/pages/page_00131.sql
@@application/pages/page_00132.sql
@@application/pages/page_00170.sql
@@application/pages/page_00171.sql
@@application/pages/page_00172.sql
@@application/pages/page_00230.sql
@@application/pages/page_00231.sql
@@application/pages/page_00250.sql
@@application/pages/page_00251.sql
@@application/pages/page_00252.sql
@@application/pages/page_00253.sql
@@application/pages/page_00254.sql
@@application/pages/page_00255.sql
@@application/pages/page_00900.sql
@@application/pages/page_00901.sql
@@application/pages/page_00902.sql
@@application/pages/page_00903.sql
@@application/pages/page_00904.sql
@@application/pages/page_00907.sql
@@application/pages/page_00908.sql
@@application/pages/page_00909.sql
@@application/pages/page_00910.sql
@@application/pages/page_00911.sql
@@application/pages/page_00912.sql
@@application/pages/page_00913.sql
@@application/pages/page_02557.sql
@@application/pages/page_09999.sql
@@application/pages/page_10060.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
